# Generated by Django 3.1.6 on 2021-06-03 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securecheck', '0015_freq'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='cert_email',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AddField(
            model_name='form',
            name='cert_purpose',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AddField(
            model_name='form',
            name='issuer_hash_old',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AddField(
            model_name='form',
            name='ocspuri',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AddField(
            model_name='form',
            name='serial_no',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AddField(
            model_name='form',
            name='sub_hash_old',
            field=models.CharField(default=None, max_length=1000),
        ),
    ]
