# Generated by Django 3.1.6 on 2021-06-07 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securecheck', '0016_auto_20210603_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='location',
            field=models.CharField(default=None, max_length=1000),
        ),
    ]
