# Generated by Django 3.1.6 on 2021-06-07 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securecheck', '0017_form_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='location_status',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
