# Generated by Django 3.1.6 on 2021-07-01 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('securecheck', '0019_auto_20210629_1056'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='thekeys',
            table=None,
        ),
    ]
