# Generated by Django 3.1.6 on 2021-07-01 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securecheck', '0020_auto_20210701_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thekeys',
            name='id',
        ),
        migrations.AddField(
            model_name='thekeys',
            name='key_id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
    ]
