# Generated by Django 3.1.6 on 2021-07-01 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securecheck', '0021_auto_20210701_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thekeys',
            name='ID',
        ),
        migrations.AddField(
            model_name='thekeys',
            name='new_ID',
            field=models.IntegerField(default=None, max_length=100),
        ),
    ]
