# Generated by Django 3.1.6 on 2021-07-01 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('securecheck', '0023_auto_20210701_2017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thekeys',
            old_name='ID',
            new_name='new_ID',
        ),
    ]
