# Generated by Django 3.1.6 on 2021-07-01 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securecheck', '0025_remove_thekeys_new_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='thekeys',
            name='ID',
            field=models.IntegerField(default=None, max_length=100),
        ),
    ]
