# Generated by Django 3.1.6 on 2021-07-01 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securecheck', '0026_thekeys_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thekeys',
            name='ID',
            field=models.IntegerField(max_length=100),
        ),
    ]
