# Generated by Django 3.1.6 on 2021-07-01 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('securecheck', '0027_auto_20210701_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thekeys',
            name='ID',
        ),
    ]
