# Generated by Django 3.1.6 on 2021-07-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securecheck', '0028_remove_thekeys_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='location',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
