# Generated by Django 3.1.6 on 2021-07-02 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securecheck', '0029_auto_20210702_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='thekeys',
            name='ID',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
