# Generated by Django 3.1.6 on 2021-05-04 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securecheck', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='secfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('month', models.CharField(max_length=100)),
                ('Not_Valid_Before', models.CharField(max_length=100)),
                ('Not_Valid_After', models.CharField(max_length=100)),
                ('Subject', models.CharField(max_length=100)),
                ('Encryption', models.CharField(max_length=100)),
                ('Status', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'finaldata',
            },
        ),
    ]
