# Generated by Django 3.1.6 on 2021-05-25 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securecheck', '0007_auto_20210525_0608'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='userid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
