# Generated by Django 3.1.6 on 2021-05-28 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securecheck', '0008_form_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='alias',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AddField(
            model_name='form',
            name='fingerprint',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AddField(
            model_name='form',
            name='issuer_hash',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AddField(
            model_name='form',
            name='modulus',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AddField(
            model_name='form',
            name='ocspid',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AddField(
            model_name='form',
            name='sub_hash',
            field=models.CharField(default=None, max_length=1000),
        ),
    ]
