# Generated by Django 3.1.6 on 2021-07-02 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('securecheck', '0032_auto_20210702_1034'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='the_keys',
            new_name='thekeys',
        ),
    ]
